version: "3.9"
services:
  POSTGRES_DB:
    image: postgres:13-alpine  

    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: fira
      POSTGRES_PASSWORD: qwerty123
    
    volumes:
      - ./data:/var/lib/postgresql/data\

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    depends_on:
      - POSTGRES_DB
  
